spring:
  application:
    name: projfinal-meow

  profiles:
    active: "@xxxx@"

  #資料庫連線設定
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=meowdb;trustServerCertificate=true;
    username: admin
    password: a123

  #Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  #圖片大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

    #spring手動設定 HTTP 請求和回應的字符編碼
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  #寵物圖片暫存路徑
file:
  tmp-upload-dir: /src/main/resources/upload/tmp/pet/images

  #寵物圖片上傳路徑
  final-upload-dir: /src/main/resources/upload/final/pet/images

  #conosle顏色
  output:
    ansi:
      enabled: always

  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: Asia/Taipei

jwt:
  token:
    expire: 10

#google座標api
google:
  api:
    key: AIzaSyATLMpyW2m1qnNAAQf0rZSpcl6TadBobBg
