spring:
  # datasource:
  #   url: jdbc:sqlserver://172.27.112.1:9433;database=meowdb;trustServerCertificate=true

  #資料庫連線設定 (localhost 要修改成部屬的主機ip)
  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=meowdb;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    redis:
      host: redis
      port: 6379

  web:
    resources:
      static-locations: classpath:/static/
