spring:
  application:
    name: projfinal-meow

  profiles:
    active: "@xxxx@"

  #資料庫連線設定
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=meowdb;trustServerCertificate=true
    username: admin
    password: a123

  #Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl		
    #圖片大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB		

  #圖片下載路徑
file:
  upload-dir: /images				

  #conosle顏色
  output:
    ansi:
      enabled: always

  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: Asia/Taipei

jwt:
  token:
    expire: 10

#google座標api
google:
  api:
    key: AIzaSyATLMpyW2m1qnNAAQf0rZSpcl6TadBobBg