spring:
  #資料庫連線設定 (localhost 要修改成部屬的主機ip)
  datasource:
    url: jdbc:sqlserver://172.27.112.1:9433;database=meowdb;trustServerCertificate=true

  #datasource:
    #url: jdbc:sqlserver://192.168.23.113:1433;database=java;trustServerCertificate=true

  web:
    resources:
      static-locations: classpath:/static/
