spring:
  #資料庫連線設定 (localhost 要修改成部屬的主機ip)
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://petfinder-sql.database.windows.net:1433;database=meowdb;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: petadmin
    password: Ab82825535

  web:
    resources:
      static-locations: classpath:/static/
